### ISSUE TITLE
Import your calendar

### ISSUE THREAD

**Issue by qchen59** [qchen59/ScheduleBot#11]
From ScheduleBot created by [lyonva](https://github.com/lyonva): lyonva/ScheduleBot#36  

Options:

- From a csv or other file
- From the output of other programs (google calendar?, .cal)
- Through connection with other services (google calendar)

**Comment by hughman98** [comment]
We discussed this issue quite a bit over discord, since we discovered that there were some issues with using tempfile() and different operating systems, which had to be resolved to add the new functionalities.

ICS files are what google calendar, and services that want to emulate google calendar, use to store events.
